### PR TITLE
Msolve parser fix

### LINKED ISSUE #3424: Msolve issues
- [x] As mentioned in https://github.com/Macaulay2/M2/pull/3392#issuecomment-2274679356, the functioni `readInteger` in [BasicPolyListParser.cpp](https://github.com/Macaulay2/M2/blob/ec9e9ac60ed4a8e791448942202f077a88a87e15/M2/Macaulay2/e/BasicPolyListParser.cpp#L41-L61) should read in arbitrary precision integers. (cc: @mikestillman)
- [x] This error should be improved:
```m2
i1 : needsPackage "Msolve"

o1 = Msolve

o1 : Package

i2 : S = QQ[x,y,h]

o2 = S

o2 : PolynomialRing

i3 : I = ideal"3x2h-x3-y3,3y2h-2x3-2y3"

               3    3     2       3     3     2
o3 = ideal (- x  - y  + 3x h, - 2x  - 2y  + 3y h)

o3 : Ideal of S

i4 : msolveRealSolutions I -- FIXME
stdio:4:19:(3): error: parallel assignment: expected a sequence of 2 values

i5 : I = ideal"3x2-x3-y3,3y2-2x3-2y3"

               3    3     2      3     3     2
o5 = ideal (- x  - y  + 3x , - 2x  - 2y  + 3y )

o5 : Ideal of S

i6 : msolveRealSolutions I -- FIXME
stdio:6:19:(3): error: parallel assignment: expected a sequence of 2 values
```
This is probably introduced by me, but in fairness I think the documentation of Msolve is unclear or has a mistake about the output in this case.

cc: @Martin-Helmer @antonleykin

### PR DESCRIPTION
**Pull request by antonleykin**
Fixed the parser for `msolve` output.
Note:
* we replace `int` with `mpz_t` and `mpz_class` where appropriate
* this change affects the classes used by `mathicgb` (but we have no issues so far)

### CODE REVIEW

**Comment by mahrud** [comment]
It passes the main example that @Martin-Helmer mentioned [here](https://github.com/Macaulay2/M2/pull/3392#issuecomment-2274579351). Could you actually add this as a test?
```m2
needsPackage "Msolve";
R=QQ[x..z,t]
K=ideal(x^6+y^6+x^4*z*t+z^3,36*x^5+60*y^5+24*x^3*z*t,
	-84*x^5+10*x^4*t-56*x^3*z*t+30*z^2,-84*y^5-6*x^4*t-18*z^2,
	48*x^5+10*x^4*z+32*x^3*z*t,48*y^5-6*x^4*z,14*x^4*z+8*x^4*t+24*z^2)
W1=msolveEliminate(R_0,K)
W2=eliminate(R_0,K)
sub(W1,R)==W2 
```

File: M2/Macaulay2/e/BasicPolyListParser.cpp [hunk 1]
```diff
@@ -59,6 +58,41 @@ long readInteger(const std::string_view& str, size_t& begin_loc, size_t end_loc)
   return result;
 }
 
+// allocates memory to (and inits) an __mpz_struct
+// void readInteger_mpz_t(mpz_t& result, const std::string_view& str, size_t& begin_loc, size_t end_loc)
```
Comment (mahrud) [inline M2/Macaulay2/e/BasicPolyListParser.cpp:62]: What's the difference between this and `readInteger_mpz_class`?

File: M2/Macaulay2/packages/Msolve/tests.m2 [hunk 2]
```diff
@@ -106,19 +106,26 @@ TEST ///
...
-  needsPackage "Msolve";
   R = QQ[x..z,t]
   K = ideal(x^6+y^6+x^4*z*t+z^3,36*x^5+60*y^5+24*x^3*z*t,
       -84*x^5+10*x^4*t-56*x^3*z*t+30*z^2,-84*y^5-6*x^4*t-18*z^2,
       48*x^5+10*x^4*z+32*x^3*z*t,48*y^5-6*x^4*z,14*x^4*z+8*x^4*t+24*z^2)
   errorDepth=2
   W1 = msolveEliminate(R_0, K, Verbosity => 1)
   W2 = eliminate(R_0, K)
-  sub(W1, R) == W2
+  assert(sub(W1, R) == W2)
```
Comment (mahrud) [inline M2/Macaulay2/packages/Msolve/tests.m2:117]: Oh, never mind, it's already here ..

**Review by mahrud — APPROVED** [review]
This looks good to me, but Mike and Martin want to take a look, too.

File: M2/Macaulay2/e/BasicPoly.hpp [hunk 3]
```diff
@@ -8,13 +8,17 @@
...
 #include <string>
 #include <unordered_map>
-  
+#include <gmpxx.h>
+
 class BasicPoly
 {
 public:
-  std::vector<int> mCoefficients;
+  std::vector<mpz_class> mCoefficients;
```
Comment (mikestillman) [inline M2/Macaulay2/e/BasicPoly.hpp:16]: The function `bytesUsed` will need to change.  We don't really need to do that before this PR is accepted, but it should be changed.

File: M2/Macaulay2/e/BasicPolyList.cpp [hunk 4]
```diff
@@ -40,7 +40,7 @@ void BasicPolyListStreamCollector::appendExponent(VarIndex index, Exponent expon
   mValue[mCurrentPoly].mMonomials[mSizeEntryInMonomial] += 2;
 }
 
-void BasicPolyListStreamCollector::appendTermDone(Coefficient coefficient)
+void BasicPolyListStreamCollector::appendTermDone(const Coefficient& coefficient)
 {
   mValue[mCurrentPoly].mCoefficients[mCurrentTerm] = coefficient;
 }
```
Comment (mikestillman) [inline M2/Macaulay2/e/BasicPolyList.cpp:46]: Is this correct?  Does this correctly copy the element? I think it probably does, just want to flag that

File: M2/Macaulay2/e/BasicPolyList.hpp [hunk 5]
```diff
@@ -25,16 +25,17 @@ long bytesUsed(const BasicPolyList& F);
 class BasicPolyListStreamCollector
 {
 public:
-  using Coefficient = int32_t;
+  using Coefficient = mpz_class;
   using VarIndex = int32_t; // TODO: these must match BasicPoly above.
   using Exponent = int32_t;
   using Component = int32_t;
+  using ModulusType = int32_t;
```
Comment (mikestillman) [inline M2/Macaulay2/e/BasicPolyList.hpp:32]: What characteristics do we want to use here?  mathic uses roughly 16 bit primes, while msolve seems to want much larger primes.  Are they still less than e.g. 2^31?

File: M2/Macaulay2/e/BasicPolyListParser.cpp [hunk 6]
```diff
@@ -184,7 +217,7 @@ void parseBasicPoly(const std::string_view& str, const IdentifierHash& idenHash,
                 {
                   throw parsing_error("expected a digit at position " + std::to_string(begin_loc));
                 }
-              e = readInteger(str, begin_loc, end_loc);
+              e = readInteger_long(str, begin_loc, end_loc);
```
Comment (mikestillman) [inline M2/Macaulay2/e/BasicPolyListParser.cpp:220]: exponent vectors are ints.  Are we silently truncating numbers to int size here?

File: M2/Macaulay2/e/coeffrings.hpp [hunk 7]
```diff
@@ -66,6 +66,15 @@ class CoefficientRingZZp : public M2::SimpleARing<CoefficientRingZZp>
     if (a < 0) a += p;
     result = log_table[a];
   }
+  
+  void set_from_mpz(elem &result, mpz_t a) const
+  {
+    mpz_t tmp;
+    mpz_init_set_si(tmp, p);        // Convert int p to mpz_t
+    mpz_mod(a, a, tmp);             // a = a mod p (always non-negative)
```
Comment (mikestillman) [inline M2/Macaulay2/e/coeffrings.hpp:74]: Maybe we should keep an mpz_t characteristic here too, so this doesn't need to be done each time?

**Review by mikestillman — APPROVED** [review]
There are a few things I will want to change in this PR, but it does fix the msolve reading large integers issue, and it doesn't mess up the mathicgb computations, so I say: let's take it.  @antonleykin and I can talk through the thoughts I have about making it more future robust.

Thanks @antonleykin for fixing that!
