### PR TITLE
Raise an error when generating random integers when Height option is nonpositive 

### LINKED ISSUE #2089: Crash on random with Height => 0
```m2
Macaulay2, version 1.17.2
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra,
               Saturation, TangentCone

i1 : random(ZZ^2, ZZ^2, Height => 0)
/home/linuxbrew/.linuxbrew/bin/M2: line 2: 1349503 Floating point exception(core dumped) LD_LIBRARY_PATH=`dirname "$0"`/../lib/Macaulay2/lib:$LD_LIBRARY_PATH `dirname "$0"`/M2-binary "$@"
```

### PR DESCRIPTION
**Pull request by d-torrance**
This fixes #2089.  Also, we now raise an error when the height is negative instead of silently taking the absolute value (which was undocumented).   The proposed behavior also matches the current behavior for random QQ's, not to mention `random(ZZ)`, which yells if the input isn't positive.

### Before

```m2
i1 : random(ZZ^5, ZZ^5, Height => -20)

o1 = | 13 10 11 3  13 |
     | 8  1  12 13 11 |
     | 16 0  1  1  7  |
     | 9  5  8  9  8  |
     | 1  16 12 15 8  |

              5       5
o1 : Matrix ZZ  <-- ZZ

i2 : random(ZZ^5, ZZ^5, Height => 0)
Floating point exception (core dumped)

Process M2 exited abnormally with code 136
```

### After
```m2
i1 : random(ZZ^5, ZZ^5, Height => -20)
stdio:1:6:(3): error: expected a positive height

i2 : random(ZZ^5, ZZ^5, Height => 0)
stdio:2:6:(3): error: expected a positive height
```

### CODE REVIEW

File: M2/Macaulay2/e/interface/random.h [hunk 1]
```diff
@@ -25,6 +25,9 @@ unsigned long rawRandomULong(unsigned long max);
 int32_t rawRandomInt(int32_t max);
 /* generate a random number in the range 0..max-1 */
 
+void rawSetRandomInteger(mpz_ptr result, gmp_ZZ maxN);
+/* if height is the null pointer, use the default height */
+
 gmp_ZZ rawRandomInteger(gmp_ZZ maxN);
 /* if height is the null pointer, use the default height */
```
Comment (d-torrance) [inline M2/Macaulay2/e/interface/random.h:33]: Add a comment: rawRandomInteger returns garbage-collected memory, and rawSetRandomInteger doesn't deal w/ garbage collection

**Comment by d-torrance** [comment]
Discussed with Mike
